### ISSUE TITLE
Typing a message in a fast channel causes your preview to disapear

### ISSUE THREAD

**Issue by Puffycheeses** [xynxynxyn/terminal-discord#11]
When typing a message, whenever a response is loaded your current entry in the input is removed. Its still there when you send but you cant see it.

This is annoying in a channel where a new message is sent every few seconds and you have to hope the message is correct because you cant view what you've typed.

**Comment by ekzyis** [comment]
I looked into it and it is harder than I thought. 
Everytime a new message is received in the channel we are currently in, it should of course be printed to the console. This happens in `show_message` which calls `console_out` at the end when all the information about the message has been parsed (timestamp, author, ...): https://github.com/xynxynxyn/terminal-discord/blob/d2ec446b7cf697038f74ad47295c79c82edf2461/index.js#L379-L381
In `console_out` we are deleting the whole last line since a longer input than the message would lead to some trailing input while the beginning is overwritten by the message. If we would not delete **and** not change the cursor position, we would just see our input in front of the message timestamp which is also not very handy.
https://github.com/xynxynxyn/terminal-discord/blob/d2ec446b7cf697038f74ad47295c79c82edf2461/index.js#L276-L281
Since I can't find a way to get the input string of `process.stdin` **before** we are deleting it but since we can enter the input string in front of the message, we may are able to pipe two streams together in a unix kind of way.
What I mean is that we can pipe the output of the current stream (which currently prints to console) into another stream which then parses the output of the previous stream and does print the whole thing in the correct order to the actual console which the user sees. This only needs to be done when we are actually inside of a channel since that is the only case where this issues arises.
@xynxynxyn I would love to help so I am very keen to see what you think about this idea.

**Comment by xynxynxyn** [comment]
This issue should finally be fixed with [a573a9a](https://github.com/xynxynxyn/terminal-discord/commit/a573a9adc914769a7ace99ade6d55a9859888b9a). If you continue having problems with this please reopen this issue.

**Comment by ekzyis** [comment]
why did you reopen the issue? it does work indeed maybe not with that commit linked here but now it works

**Comment by ekzyis** [comment]
Why did you reopen that issue? It does work like intended now.

**Comment by xynxynxyn** [comment]
I forgot to close it again but it should work now with commit [4887fc1](https://github.com/xynxynxyn/terminal-discord/commit/4887fc125a0e0ee97df1c7de971ba080fa761d80).
